runtime: python312
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
- url: /.*
  script: auto

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .95
  target_throughput_utilization: .95
  min_pending_latency: 300ms
  max_pending_latency: 15000ms
  max_concurrent_requests: 80

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
