application: web-fiddle
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: /apple-touch-icon.png
  static_files: static/images/apple-touch-icon.png
  upload: static/images/apple-touch-icon.png

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

instance_class: F2
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
